<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <name>${project.groupId}:${project.artifactId}</name>
    <description>Example application showing how to document a jEAP microservice with the jEAP swagger starter
        (springdoc-openapi): OpenAPI definition, grouped and versioned APIs and an interactive Swagger UI with OAuth 2.0
        login.
    </description>
    <modelVersion>4.0.0</modelVersion>
    <url>https://github.com/jme-admin-ch/jme-swagger-example/tree/main</url>
    <scm>
        <url>https://github.com/jme-admin-ch/jme-swagger-example.git</url>
        <connection>scm:git:git://github.com/jme-admin-ch/jme-swagger-example.git</connection>
        <developerConnection>scm:git:ssh://github.com:jme-admin-ch/jme-swagger-example.git</developerConnection>
    </scm>
    <developers>
        <developer>
            <name>BIT</name>
            <email>jeap-community@bit.admin.ch</email>
            <organization>Federal Office of Information Technology, Systems and Telecommunication FOITT</organization>
            <organizationUrl>https://www.bit.admin.ch/</organizationUrl>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
    </licenses>

    <artifactId>jme-swagger-example</artifactId>
    <version>3.2.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>ch.admin.bit.jeap</groupId>
        <artifactId>jeap-spring-boot-parent</artifactId>
        <version>39.5.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <modules>
        <module>jme-swagger-service</module>
        <module>jme-swagger-auth-scs</module>
        <module>jme-swagger-test</module>
    </modules>

    <properties>
        <jme-spring-boot-integration-test.version>5.14.0</jme-spring-boot-integration-test.version>
        <maven.javadoc.skip>false</maven.javadoc.skip>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>jme-swagger-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>jme-swagger-auth-scs</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>jme-swagger-test</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <!-- Add license to jar manifest -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <configuration>
                        <archive>
                            <manifestEntries>
                                <Bundle-License>https://www.apache.org/licenses/LICENSE-2.0</Bundle-License>
                            </manifestEntries>
                        </archive>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <!-- Check third-party license compliance -->
            <plugin>
                <groupId>org.honton.chas</groupId>
                <artifactId>license-maven-plugin</artifactId>
            </plugin>
            <!-- Generate third-party license list and check for missing license information -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
